module.exports = {
  create: [
    {
      model: 'name',
      required: true,
      type: 'string',
      label: 'Student Name',
      minLength: 3,
      maxLength: 50,
      message: 'Name must be between 3 and 50 characters.',
    },
    {
      model: 'age',
      required: true,
      type: 'number',
      label: 'Student Age',
      min: 5,
      max: 100,
      message: 'Age must be between 5 and 100 years.',
    },
    {
      model: 'grade',
      required: true,
      type: 'string',
      label: 'Grade',
      minLength: 1,
      maxLength: 10,
      message: 'Grade must be between 1 and 10 characters.',
    },
    {
      model: 'schoolId',
      required: true,
      type: 'string',
      label: 'School ID',
      minLength: 10,
      maxLength: 100,
      message: 'School ID must be valid.',
    },
    {
      model: 'classId',
      required: true,
      type: 'string',
      label: 'Classroom ID',
      minLength: 10,
      maxLength: 100,
      message: 'Classroom ID must be valid.',
    },
    {
      model: 'profile',
      required: false,
      type: 'object',
      label: 'Student Profile',
      message: 'Profile must be a valid JSON object.',
    },
  ],

  update: [
    {
      model: 'name',
      required: false,
      type: 'string',
      label: 'Student Name',
      minLength: 3,
      maxLength: 50,
      message: 'Name must be between 3 and 50 characters.',
    },
    {
      model: 'age',
      required: false,
      type: 'number',
      label: 'Student Age',
      min: 5,
      max: 100,
      message: 'Age must be between 5 and 100 years.',
    },
    {
      model: 'grade',
      required: false,
      type: 'string',
      label: 'Grade',
      minLength: 1,
      maxLength: 10,
      message: 'Grade must be between 1 and 10 characters.',
    },
    {
      model: 'profile',
      required: false,
      type: 'object',
      label: 'Student Profile',
      message: 'Profile must be a valid JSON object.',
    },
  ],

  delete: [
    {
      model: 'studentId',
      required: true,
      type: 'string',
      label: 'Student ID',
      minLength: 10,
      maxLength: 100,
      message: 'Student ID must be valid.',
    },
  ],
}
