name: CD to Heroku

on:
  push:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code
      - name: Checkout
        uses: actions/checkout@v2

      # 2. Set up Node
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # (Optional) 4. Run tests
      # - name: Run tests
      #   run: npm test

      # 5. Install Heroku CLI
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      # 6. Log in to Heroku
      - name: Login to Heroku
        run: echo "${{ secrets.HEROKU_API_KEY }}" | heroku login --with-token

      # 7. Create (or check) Heroku app
      - name: Create Heroku App
        run: |
          heroku apps:info -a ${{ secrets.HEROKU_APP_NAME }} || heroku create ${{ secrets.HEROKU_APP_NAME }}

      # 8. Set Heroku config vars
      - name: Set Heroku config vars
        run: |
          heroku config:set \
            SERVICE_NAME=SCHOOL \
            ENV=production \
            USER_PORT=5111 \
            ADMIN_PORT=5222 \
            ADMIN_URL=http://localhost:5222 \
            REDIS_URI=${{ secrets.REDIS_URI }} \
            CORTEX_REDIS=${{ secrets.CORTEX_REDIS }} \
            CORTEX_PREFIX=${{ secrets.CORTEX_PREFIX }} \
            CORTEX_TYPE=${{ secrets.CORTEX_TYPE }} \
            OYSTER_REDIS=${{ secrets.OYSTER_REDIS }} \
            OYSTER_PREFIX=${{ secrets.OYSTER_PREFIX }} \
            CACHE_REDIS=${{ secrets.CACHE_REDIS }} \
            CACHE_PREFIX=${{ secrets.CACHE_PREFIX }} \
            MONGO_URI=${{ secrets.MONGO_URI }} \
            LONG_TOKEN_SECRET=${{ secrets.LONG_TOKEN_SECRET }} \
            SHORT_TOKEN_SECRET=${{ secrets.SHORT_TOKEN_SECRET }} \
            NACL_SECRET=${{ secrets.NACL_SECRET }} \
            -a ${{ secrets.HEROKU_APP_NAME }}

      # 9. Deploy to Heroku
      - name: Deploy to Heroku
        run: |
          heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}
          git push heroku HEAD:main -f
